### ISSUE TITLE
[Suggestion] Improved code quality and feedback

### ISSUE THREAD

**Issue by ferion11** [AppImage/zsync2#49]
Hi! I have a few suggestions for improving code quality and feedback:

*  Make the travis-ci badge show on README.md file;
*  Make coverage tests, integrate with https://codecov.io (free to opensource) and show the badge on README.md file too;
The codecov have a bot that shows up on pull requests that reduced the coverage tests, indicating issues that are hard to see on the code.
*  Integrate https://codacy.com (free to opensource) and show the badge on README.md file too;
The codacy will analyse the code and give a lot of information to improve the quality of the code.

The badges are just easy to see feedbacks.
If you don't like that kind of thing, then just ignore this suggestion and close this suggestion.

**Comment by TheAssassin** [comment]
The lack of unit tests means we have no test coverage to report. Also, I dislike the services you mentioned as that's more closed-source software used to build free software (a problem I see with GitHub and especially Travis, too).

Regarding the inclusion of a Travis badge, please send a PR, I don't mind including a badge. This project is updated very infrequently, though, mostly due to the lack of time.
